-- Script SQL pour MariaDB

CREATE DATABASE IF NOT EXISTS PRESENCE;
USE PRESENCE;

-- Table BADGE
CREATE TABLE BADGE (
    idBadge INT AUTO_INCREMENT PRIMARY KEY,
    idSTRI INT NOT NULL,
    macBLE VARCHAR(50) NOT NULL,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL
);

-- Table SALLE
CREATE TABLE SALLE (
    idSalle INT AUTO_INCREMENT PRIMARY KEY,
    nomSalle VARCHAR(50) NOT NULL,
    numeroSalle INT NOT NULL,
    Etage INT NOT NULL
);

-- Table COURS
CREATE TABLE COURS (
    idCours INT AUTO_INCREMENT PRIMARY KEY,
    Libelle VARCHAR(100) NOT NULL,
    DateInit DATE NOT NULL,
    DateFin DATE NOT NULL,
    idSalle INT NOT NULL,
    FOREIGN KEY (idSalle) REFERENCES SALLE(idSalle)
);

-- Table DETECTEUR
CREATE TABLE DETECTEUR (
    idDetecteur INT AUTO_INCREMENT PRIMARY KEY,
    macBLE VARCHAR(50) NOT NULL,
    macWIFI VARCHAR(50) NOT NULL,
    Type ENUM('Porte', 'Présence') NOT NULL,
    idSalle INT NOT NULL,
    FOREIGN KEY (idSalle) REFERENCES SALLE(idSalle)
);

-- Table PRESENCE
CREATE TABLE PRESENCE (
    idPresence INT AUTO_INCREMENT PRIMARY KEY,
    idCours INT NOT NULL,
    idBadge INT NOT NULL,
    FOREIGN KEY (idCours) REFERENCES COURS(idCours),
    FOREIGN KEY (idBadge) REFERENCES BADGE(idBadge)
);